apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: descheduler
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: descheduler
    spec:
      project: "default"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - PruneLast=true
      source:
        repoURL: https://github.com/schalla0791/cluster-addons.git
        targetRevision: HEAD
        path: descheduler
        helm:
          valueFiles:
          - values.yaml
      destination:
        server: '{{url}}'
        namespace: kube-system
