---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: ingress-nginx
    spec:
      project: "default"
      syncPolicy:
#        automated:
#          prune: true
#          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - PruneLast=true
      source:
        repoURL: https://github.com/schalla0791/cluster-addons.git
        targetRevision: HEAD
        path: ingress-nginx
        helm:
          valueFiles:
          - values.yaml
      destination:
        server: '{{url}}'
        namespace: ingress-nginx
