apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-prometheus-stack-crds
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: kube-prometheus-stack-crds
    spec:
      project: "default"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - Replace=true
        - CreateNamespace=true
      source:
        repoURL: https://github.com/prometheus-community/helm-charts.git
        path: charts/kube-prometheus-stack/crds/
        targetRevision: "kube-prometheus-stack-40.1.0"
        directory:
          recurse: true
      destination:
        server: '{{url}}'
        namespace: observability
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: prometheus
    spec:
      project: "default"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - PruneLast=true
        - CreateNamespace=true
      source:
        repoURL: https://github.com/schalla0791/cluster-addons.git
        targetRevision: HEAD
        path: prometheus
        helm:
          skipCrds: true
          valueFiles:
          - values.yaml
      destination:
        server: '{{url}}'
        namespace: observability
